// Firebase configuration for Warranty Vault.
// Generated by `flutterfire configure` — do not edit manually.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        // Web preview + Android are the only supported targets for now.
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmczKi0j_yOA5QrIT5DFkBi8CIgeveBU',
    appId: '1:916872583271:web:fb7eaf6e4940bce52adcc2',
    messagingSenderId: '916872583271',
    projectId: 'warrenty-management-b9396',
    authDomain: 'warrenty-management-b9396.firebaseapp.com',
    storageBucket: 'warrenty-management-b9396.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNPHO-pgWSrZDXn60_ZN01OF5Jo28Kso',
    appId: '1:916872583271:android:81e74c84ed95e0bc2adcc2',
    messagingSenderId: '916872583271',
    projectId: 'warrenty-management-b9396',
    databaseURL: 'https://warrenty-management-b9396-default-rtdb.firebaseio.com',
    storageBucket: 'warrenty-management-b9396.firebasestorage.app',
  );
}
